### ISSUE TITLE
AttributeError: 'module' object has no attribute 'hybridmethod'

### ISSUE THREAD

**Issue by elfring** [onyxfish/csvkit#256]
The command "csvcut" works with the few functions I tried out as expected also on my openSUSE system. But I stumble on the following error message.
```
elfring@Sonne:~/Projekte/Coccinelle/janitor> csvsql --verbose
Traceback (most recent call last):
  File "/usr/bin/csvsql", line 9, in <module>
    load_entry_point('csvkit==0.6.1', 'console_scripts', 'csvsql')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/csvkit/utilities/csvsql.py", line 6, in <module>
    from csvkit import sql
  File "/usr/lib/python2.7/site-packages/csvkit/sql.py", line 6, in <module>
    from sqlalchemy import Column, MetaData, Table, create_engine
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/__init__.py", line 52, in <module>
    from sqlalchemy.types import (
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/types.py", line 27, in <module>
    from sqlalchemy import exc, schema
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/schema.py", line 33, in <module>
    from sqlalchemy import event, events
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/event/__init__.py", line 7, in <module>
    from .api import CANCEL, NO_RETVAL, listen, listens_for, remove, contains
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/event/api.py", line 13, in <module>
    from .base import _registrars
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/event/base.py", line 42, in <module>
    class _Dispatch(object):
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/event/base.py", line 104, in _Dispatch
    @util.hybridmethod
AttributeError: 'module' object has no attribute 'hybridmethod'
```

**Comment by sheepsy90** [comment]
I have the same issue on Ubuntu Linux  - Maybe a Crossreference with another flask module

**Comment by gzk07** [comment]
i got the same problems...dose anyone know what is this?

**Comment by jpmckinney** [comment]
Can anyone please paste the command that they run to trigger this error?

Runnin `csvsql --verbose` (from @elfring) on my system produces no error.

**Comment by elfring** [comment]
In which time frame may I expect an appropriate reaction (like an error message) for the simple command variant "`csvsql --verbose`" for another try of the software "csvkit 0.9.1" on my current openSUSE Tumbleweed system?

**Comment by jpmckinney** [comment]
If you run `csvsql --verbose` on its own, it waits for input from stdin. So it seems like there is no error when you run it.

**Comment by elfring** [comment]
@jpmckinney: The command "`csvsql --verbose`" might work as expected then now. Should I get any indication that further data are expected from the channel "standard input"?

**Comment by jpmckinney** [comment]
A prompt may be appropriate. Created #517 as this affects all the tools. Closing unless I hear of people still experiencing the error.
