### ISSUE TITLE
in2csv ne_1033_data.xlsx => unsupported operand error

### ISSUE THREAD

**Issue by nryberg** [onyxfish/csvkit#345]
When I try to run the example code:
```
in2csv ne_1033_data.xlsx 
```
I get:
```
unsupported operand type(s) for +: 'NoneType' and 'int'
```
I've brew installed Python and reinstalled (pip) the csvkit.

**Comment by jpmckinney** [comment]
No news in over a year. Happy to re-open if anyone can run `in2csv` with the `-v` argument so that we can see the error traceback.

**Comment by zenon1234** [comment]
here's the in2csv -v output:

Traceback (most recent call last):
  File "/usr/local/bin/in2csv", line 9, in <module>
    load_entry_point('csvkit==0.8.0', 'console_scripts', 'in2csv')()
  File "/usr/local/lib/python2.7/dist-packages/csvkit/utilities/in2csv.py", line 82, in launch_new_instance
    utility.main()
  File "/usr/local/lib/python2.7/dist-packages/csvkit/utilities/in2csv.py", line 76, in main
    data = convert.convert(self.input_file, filetype, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/csvkit/convert/__init__.py", line 38, in convert
    return xlsx2csv(f, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/csvkit/convert/xlsx.py", line 58, in xlsx2csv
    for i, row in enumerate(sheet.iter_rows()):
  File "/usr/local/lib/python2.7/dist-packages/openpyxl/worksheet/worksheet.py", line 423, in iter_rows
    max_col + column_offset,
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by jpmckinney** [comment]
@zenon1234 That seems to be using csvkit 0.8.0, which is very old.
