### ISSUE TITLE
sql2csv mysql UnicodeDecodeError

### ISSUE THREAD

**Issue by sanderm** [onyxfish/csvkit#352]
$ sql2csv --db mysql://username:password@localhost/dbname' --query "select 'ø'"

gives:

Your file is not "utf-8" encoded. Please specify the correct encoding with the -e flag. Use the -v flag to see the complete error.

When I try with -v I get the compleate error message:

$ sql2csv  -v --db mysql://username:password@localhost/dbname' --query "select 'ø'"

gives:
```
Traceback (most recent call last):
  File "/usr/local/bin/sql2csv", line 9, in <module>
    load_entry_point('csvkit==1.0.0', 'console_scripts', 'sql2csv')()
  File "build/bdist.linux-x86_64/egg/csvkit/utilities/sql2csv.py", line 64, in launch_new_instance
  File "build/bdist.linux-x86_64/egg/csvkit/utilities/sql2csv.py", line 58, in main
  File "build/bdist.linux-x86_64/egg/csvkit/py2.py", line 46, in writerow
  File "build/bdist.linux-x86_64/egg/csvkit/unicsv.py", line 90, in writerow
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```
$ echo $LANG
en_US.UTF-8

but when I try with the sqllite driver, then it works:

$ sql2csv -v --db "sqlite:///dummy.db" --query "select 'ø'"
'ø'
ø

**Comment by abbypan** [comment]
when database use utf-8, and rows contain non ascii char, also occur same error

**Comment by edwardros** [comment]
I can second abbypan's issue:
Postgres version: 8.3.11
Python Version: 2.7.3
CSV Kit Version: 0.9.1

    createdb -h host -U user database
    psql -h host -U user database -c "create table test (name varchar)"
    psql -h host -U user database -c "insert into test values ('’')"
    sql2csv --db 'postgres://user@host/database' --query "SELECT * from test" -v

Stacktrace:

    Traceback (most recent call last):
      File "/user/bin/sql2csv", line 9, in <module>
        load_entry_point('csvkit==0.9.1', 'console_scripts', 'sql2csv')()
      File "/user/lib/python2.7/site-packages/csvkit/utilities/sql2csv.py", line 65, in launch_new_instance
        utility.main()
      File "/user/lib/python2.7/site-packages/csvkit/utilities/sql2csv.py", line 58, in main
        for row in rows:
      File "/user/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 713, in __iter__
        row = self.fetchone()
      File "/user/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 1026, in fetchone
        self.cursor, self.context)
      File "/user/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1344, in _handle_dbapi_exception
        util.reraise(*exc_info)
      File "/user/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 1017, in fetchone
        row = self._fetchone_impl()
      File "/user/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 898, in _fetchone_impl
        return self.cursor.fetchone()
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

**Comment by fedeisas** [comment]
Having the same problem over here :-(

**Comment by edwardros** [comment]
I can confirm it is an issue when the database is not UTF-8 encoded (I have successfully retrieved unicode characters from a non-UTF-8 encoded database).

I imagine one solution would be to add an option to pass the encoding as a command line argument at run time, and code strings appropriately using sqlalchemy.

**Comment by fedeisas** [comment]
@edwardros +1

I fixed it using encoding on the sqlalchemy connection string:
`sql2csv --db 'mysql://user:pass@host/database?encoding=utf8'`

**Comment by jehrhardt** [comment]
@fedeisas workaround looks nice. Maybe this could make into the documentation.

**Comment by dudleycarr** [comment]
The connection string workaround yields a `'encoding' is an invalid keyword argument for this function.` error. I'm running the latest of csvkit installed via pip on MacOSX against a MySQL db with python 2.7.

**Comment by dudleycarr** [comment]
I found this:
http://docs.sqlalchemy.org/en/latest/dialects/mysql.html#unicode-encoding-decoding

It seems that the right argument is `charset` not `encoding` for MySQL databases.

**Comment by jpmckinney** [comment]
Issue has gone away, likely due to #486
