### ISSUE TITLE
Install trouble in El Capitan

### ISSUE THREAD

**Issue by kleinmatic** [onyxfish/csvkit#460]
Getting this error when I try to install. My mac is bound to an Active Directory domain, adding to the fun I'm sure. 

>sudo -H pip install csvkit
Collecting csvkit
  Using cached csvkit-0.9.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): xlrd>=0.7.1 in /Library/Python/2.7/site-packages (from csvkit)
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy>=0.6.6 in /Library/Python/2.7/site-packages (from csvkit)
Requirement already satisfied (use --upgrade to upgrade): openpyxl==2.2.0-b1 in /Library/Python/2.7/site-packages (from csvkit)
Collecting six>=1.6.1 (from csvkit)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting python-dateutil==2.2 (from csvkit)
  Using cached python-dateutil-2.2.tar.gz
Collecting dbf==0.94.003 (from csvkit)
  Using cached dbf-0.94.003.tar.gz
Requirement already satisfied (use --upgrade to upgrade): jdcal in /Library/Python/2.7/site-packages (from openpyxl==2.2.0-b1->csvkit)
Installing collected packages: six, python-dateutil, dbf, csvkit
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-Hn6Efo-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

**Comment by PLPeeters** [comment]
I confirm this issue.

**Comment by camkidman** [comment]
I'm getting the same issue as well:

```
OSError: [Errno 1] Operation not permitted: '/tmp/pip-jJlgW6-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

Seems like running a `brew install python` and then running `pip install csvkit` solves the problem. I imagine that will keep it from using the default system python and use the brew installed version instead. 

More information about the system integrity protection(which is causing the issue) here: https://support.apple.com/en-us/HT204899

**Comment by kleinmatic** [comment]
@camkidman Yah, I confirm that fix. Looks like system integrity protection in El Cap is considered harmful. I installed the homebrew version of python and everything is better now. Thanks.

**Comment by PLPeeters** [comment]
It's more of a workaround than a solution, so I don't think this should be closed.

**Comment by Fil** [comment]
yup — same problem
