### ISSUE TITLE
in2csv error: "AttributeError: 'module' object has no attribute 'biffh'" 

### ISSUE THREAD

**Issue by mpettis** [onyxfish/csvkit#462]
I am getting the following error when just trying to look at the help for `in2csv`.  Ubuntu and Python version information precede the error.  `csvkit` installed via `pip`.

    mpettis@usbb8d4ecdceb9:~$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 14.04.3 LTS
    Release:        14.04
    Codename:       trusty

    mpettis@usbb8d4ecdceb9:~$ python -V
    Python 2.7.10

    mpettis@usbb8d4ecdceb9:~$ in2csv --help
    Traceback (most recent call last):
      File "/usr/local/bin/in2csv", line 7, in <module>
        from csvkit.utilities.in2csv import launch_new_instance
      File "/usr/local/lib/python2.7/dist-packages/csvkit/utilities/in2csv.py", line 3, in <module>
        from csvkit import convert
      File "/usr/local/lib/python2.7/dist-packages/csvkit/convert/__init__.py", line 10, in <module>
        from csvkit.convert.xls import xls2csv
      File "/usr/local/lib/python2.7/dist-packages/csvkit/convert/xls.py", line 100, in <module>
        xlrd.biffh.XL_CELL_EMPTY: normalize_empty,
    AttributeError: 'module' object has no attribute 'biffh'

**Comment by mpettis** [comment]
This was an install issue.  I had a VM with a python version of 2.7.6 (iirc) and built my own version from source for 2.7.10 for use with other constraints.  The issue I had was that 1.) `python` was still soft-linked to the old version in `/usr/bin`, and 2.) `pip` uses a shebang line of:

    #!/usr/bin/python

rather than

    #!/usr/bin/env python

So, even though I had altered my `$PATH` variable to put the new python at an earlier precedence in the search path, pip was working with the old version, which caused all sorts of problems.  Once I reinstalled `easy_install.py` and `pip` with the newer python version soft-linked, it all came out fine.

Just a reference here in case this error comes up and someone comes looking for answers...
