### ISSUE TITLE
UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

### ISSUE THREAD

**Issue by mhwombat** [onyxfish/csvkit#477]
On a CentOS system:

```
$ cat temp.csv
time,Δv,blah
1,1,1
2,2,2
3,3,3
$ csvcut -c "time,Δv" temp.csv
/usr/lib/python2.7/site-packages/csvkit/cli.py:296: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if isinstance(c, six.string_types) and not c.isdigit() and c in column_names:
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/csvkit/cli.py", line 262, in handler
    sys.stderr.write('%s\n' % six.text_type(value))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 19: ordinal not in range(128)

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/csvcut", line 9, in <module>
    load_entry_point('csvkit==0.9.1', 'console_scripts', 'csvcut')()
  File "/usr/lib/python2.7/site-packages/csvkit/utilities/csvcut.py", line 64, in launch_new_instance
    utility.main()
  File "/usr/lib/python2.7/site-packages/csvkit/utilities/csvcut.py", line 48, in main
    column_ids = parse_column_identifiers(self.args.columns, column_names, self.args.zero_based, self.args.not_columns)
  File "/usr/lib/python2.7/site-packages/csvkit/cli.py", line 338, in parse_column_identifiers
    columns.append(match_column_identifier(column_names, c, zero_based))
  File "/usr/lib/python2.7/site-packages/csvkit/cli.py", line 305, in match_column_identifier
    raise ColumnIdentifierError('Column identifier "%s" is neither an integer, nor a existing column\'s name.' % c)
csvkit.exceptions.ColumnIdentifierError:
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_IE.UTF-8"
LC_NUMERIC="en_IE.UTF-8"
LC_TIME="en_IE.UTF-8"
LC_COLLATE="en_IE.UTF-8"
LC_MONETARY="en_IE.UTF-8"
LC_MESSAGES="en_IE.UTF-8"
LC_PAPER="en_IE.UTF-8"
LC_NAME="en_IE.UTF-8"
LC_ADDRESS="en_IE.UTF-8"
LC_TELEPHONE="en_IE.UTF-8"
LC_MEASUREMENT="en_IE.UTF-8"
LC_IDENTIFICATION="en_IE.UTF-8"
LC_ALL=en_IE.UTF-8
```

**Comment by mhwombat** [comment]
I installed the github version of csvkit and got the same result:

```
$ csvcut -c "time,Δv" temp.csv
/home/amy/csvkit/csvkit/cli.py:296: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if isinstance(c, six.string_types) and not c.isdigit() and c in column_names:
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/amy/csvkit/csvkit/cli.py", line 262, in handler
    sys.stderr.write('%s\n' % six.text_type(value))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 19: ordinal not in range(128)

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/csvcut", line 9, in <module>
    load_entry_point('csvkit==0.9.2', 'console_scripts', 'csvcut')()
  File "/home/amy/csvkit/csvkit/utilities/csvcut.py", line 64, in launch_new_instance
    utility.main()
  File "/home/amy/csvkit/csvkit/utilities/csvcut.py", line 48, in main
    column_ids = parse_column_identifiers(self.args.columns, column_names, self.args.zero_based, self.args.not_columns)
  File "/home/amy/csvkit/csvkit/cli.py", line 338, in parse_column_identifiers
    columns.append(match_column_identifier(column_names, c, zero_based))
  File "/home/amy/csvkit/csvkit/cli.py", line 305, in match_column_identifier
    raise ColumnIdentifierError('Column identifier "%s" is neither an integer, nor a existing column\'s name.' % c)
csvkit.exceptions.ColumnIdentifierError: 
```

**Comment by jpmckinney** [comment]
Fixed by #486

**Comment by wbzyl** [comment]
This does not work csvkit (0.9.1):
```sh
csvgrep -c 'Δv' -m '2' test.csv
echo -e 'я\nsome Вася' | csvgrep -c я -m some
```
Apparently unicode does not work with `-c` option.

```
csvgrep -c "Δv" -m 2 test.csv
/usr/local/lib/python2.7/site-packages/csvkit/cli.py:296: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if isinstance(c, six.string_types) and not c.isdigit() and c in column_names:
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/csvkit/cli.py", line 262, in handler
    sys.stderr.write('%s\n' % six.text_type(value))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 19: ordinal not in range(128)

echo -e 'я\nsome Вася' | csvgrep -c я -m some
/usr/local/lib/python2.7/site-packages/csvkit/cli.py:296: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if isinstance(c, six.string_types) and not c.isdigit() and c in column_names:
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/csvkit/cli.py", line 262, in handler
    sys.stderr.write('%s\n' % six.text_type(value))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 19: ordinal not in range(128)
```

**Comment by jpmckinney** [comment]
You need to use the unreleased version in GitHub for now.
