### ISSUE TITLE
Local tox is failing trying to find `README.md`

### ISSUE THREAD

**Issue by onyxfish** [onyxfish/csvkit#512]
But not failing on Travis:

```
Processing ./.tox/dist/csvkit-1.0.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/folders/hh/rmrbcxcd40s76wf14g4n1cfm232l1d/T/pip-lnNibY-build/setup.py", line 23, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
```

Are you seeing this @jpmckinney?

**Comment by jpmckinney** [comment]
Possibly needs to be added to MANIFEST.in? https://github.com/onyxfish/csvkit/pull/487/files

**Comment by onyxfish** [comment]
Hmmm, that would be new by me. I've never even had one of those before and this issue just started.

**Comment by onyxfish** [comment]
Merging it in anyway

**Comment by onyxfish** [comment]
I stand corrected. Python packaging: the eternal mystery.
